# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
ast = true
auto_detect_solc = false
build_info = true
bytecode_hash = "none"
evm_version = "paris"
extra_output = ["storageLayout"]
extra_output_files = ["metadata"]
fs_permissions = [{ access = "read", path = "./test/fixtures"}, { access = "read", path = "./out"}]
ffi = true
fuzz = { runs = 256 }
gas_reports = ["*"]
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 200
out = "out"
script = "script"
src = "src"
test = "test"
via_ir = true

[profile.coverage]
fuzz = { runs = 256 }
verbosity = 3

[profile.ci]
fuzz = { runs = 1_000 }
verbosity = 3

[fmt]
bracket_spacing = true
hex_underscores = "remove"
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
override_spacing = true
quote_style = "double"
single_line_statement_blocks = "multi"
sort_imports = true
tab_width = 4
wrap_comments = true

[rpc_endpoints]
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
amoy = "https://polygon-amoy.g.alchemy.com/v2/UurQT_ACJmrq7V1qhfR43IAypZlMeeLm"

[etherscan]
polygon = { key = "${ETHERSCAN_API_KEY}" }
amoy = { key = "${ETHERSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
