[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.28"
via_ir = true
optimizer = true
optimizer-runs = 200
ast = true
ffi = true
fs_permissions = [{ access = "read", path = "./test/fixtures"}]

