// SPDX-License-Identifier: MIT
pragma solidity 0.8.34;

import { Vm } from "forge-std/Vm.sol";
import { PhaseSeed, PricePhase } from "src/interfaces/IFANtiumAthletes.sol";

/**
 * @notice Loads `test/fixtures/phase-seeds.json` (generated by `scripts/generatePhaseSeeds.ts` from
 *         the Strapi discount sections) into the `PhaseSeed[]` consumed by
 *         `FANtiumAthletesV12.initializeV12`.
 */
library PhaseSeedsFixture {
    /**
     * @notice JSON mirror structs: Foundry decodes JSON objects with keys in alphabetical order,
     *         which does not match the field order of `PricePhase`.
     */
    struct PricePhaseJson {
        uint256 maxInvocations;
        uint256 price;
    }

    struct PhaseSeedJson {
        uint256 collectionId;
        PricePhaseJson[] phases;
    }

    function load(Vm vm) internal view returns (PhaseSeed[] memory seeds) {
        string memory path = string.concat(vm.projectRoot(), "/test/fixtures/phase-seeds.json");
        PhaseSeedJson[] memory raw = abi.decode(vm.parseJson(vm.readFile(path)), (PhaseSeedJson[]));

        seeds = new PhaseSeed[](raw.length);
        for (uint256 i = 0; i < raw.length; i++) {
            seeds[i].collectionId = raw[i].collectionId;
            seeds[i].phases = new PricePhase[](raw[i].phases.length);
            for (uint256 j = 0; j < raw[i].phases.length; j++) {
                seeds[i].phases[j] = PricePhase({
                    price: uint128(raw[i].phases[j].price), maxInvocations: uint128(raw[i].phases[j].maxInvocations)
                });
            }
        }
    }
}
